# NixOS configuration for OrbStack VM
# Local development VM on macOS
# Meant to be applied from inside the VM: sudo nixos-rebuild switch --impure --flake .#orbstack --option filter-syscalls false
{
  modulesPath,
  config,
  pkgs,
  lib,
  ...
}:
{
  imports = [
    (modulesPath + "/virtualisation/lxc-container.nix")
    # Include the OrbStack-specific autogenerated configuration
    # These files should exist in /etc/nixos/ on the OrbStack VM
    /etc/nixos/incus.nix
    /etc/nixos/orbstack.nix
  ];

  # System state version
  system.stateVersion = "25.05";

  # Time zone
  time.timeZone = "Europe/Zurich";

  # Enable zsh and direnv
  programs.zsh.enable = true;
  programs.nix-ld.enable = true;

  # OrbStack-specific user configuration
  users.users.stanmart = {
    uid = 501;
    extraGroups = [ "wheel" "orbstack" ];
    # simulate isNormalUser, but with an arbitrary UID
    isSystemUser = true;
    group = "users";
    createHome = true;
    home = "/home/stanmart";
    homeMode = "700";
    shell = pkgs.zsh;
    openssh.authorizedKeys.keys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICUXDcdw+FfLyMYNWmKs/j0LPAI4N29QzRJr92eR0vmK"
      "sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAIOPnYdF6Hbom3qxjSiM6mzXA6Luv5SB8N4v2axhgoYnvAAAABHNzaDo="
    ];
  };

  # OrbStack group
  users.groups.orbstack.gid = 67278;

  # This being `true` leads to a few nasty bugs in OrbStack
  users.mutableUsers = false;

  # Passwordless sudo for convenience in development VM
  security.sudo.wheelNeedsPassword = false;

  # Disable root password for security
  users.users.root.hashedPassword = "!";

  # Enable nix flakes
  nix.settings.experimental-features = [ "nix-command" "flakes" ];
}
